#!/usr/bin/env bash
#Install nginx web server

sudo apt-update -y
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > index.nginx-debian.html
sudo mv index.html /var/www/html/
sudo service nginx start

