#!/usr/bin/env bash
#Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo mv index.nginx-debian.html /var/www/html/
Service="\\\tlocation /redirect_me{\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "26i $Service" /etc/nginx/sites-available/default
Server="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "29i $Server" /etc/nginx/sites-available/default
header="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "79i $header" /etc/nginx/sites-available/default
sudo service nginx start
