#!/usr/bin/env bash
#fixing what’s keeping the Ubuntu container’s Nginx installation from listening on port 80                                                                       
                                                                                          
sudo rm /etc/nginx/sites-enabled/default                                                  
                                                                                          
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default                 
                                                                                          
sudo service nginx start   
